spring:
  application:
    name: Industrial_Innovation_Engine_server
  datasource:
    url: jdbc:mysql://10.168.89.204:3306/IIE?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: Huawei@311
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

server:
  port: 5174


mybatis:
  configuration:
    # 使用下划线转驼峰命名
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.IIE.Industrial_Innovation_Engine_server.entity
